component/historian:
  - cmd/historian/*
  - internal/historian/*
  - internal/plugins/providers/historical/*
  - plg/querybuilder/*

component/runtime-sidecar:
  - runtime/*
  - pkg/runtimemanager/*

component/engine:
    - internal/engine/**

component/labsdk:
  - labsdk/*

provider/redis:
  - internal/plugins/providers/state/redis/*
provider/snowflake:
  - internal/plugins/providers/historical/snowflake/*
provider/aws:
  - internal/plugins/providers/historical/parquet/s3/*