resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
- name: controller
  newName: ghcr.io/natun-ai/natun
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
