# permissions for end users to edit datasources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datasource-editor-role
rules:
  - apiGroups:
      - k8s.raptor.ml
    resources:
      - datasources
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.raptor.ml
    resources:
      - datasources/status
    verbs:
      - get
