# permissions for end users to edit models.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: model-editor-role
rules:
  - apiGroups:
      - k8s.raptor.ml
    resources:
      - models
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.raptor.ml
    resources:
      - models/status
    verbs:
      - get
