apiVersion: k8s.raptor.ml/v1alpha1
kind: Feature
metadata:
  name: user-city
spec:
  primitive: string
  freshness: 720h #30 days
  staleness: 2160h #90 days
  dataSource:
    name: json-placeholder
  builder:
    code: |
      def handler(**req):
        return req["payload"]["address"]["city"]
