apiVersion: k8s.natun.ai/v1alpha1
kind: Feature
metadata:
  name: user-city
spec:
  primitive: int
  freshness: 720h #30 days
  staleness: 2160h #90 days
  builder:
    kind: rest
    url: https://jsonplaceholder.typicode.com/users/{entity_id}/
    method: GET
    body: ~
    expression: |
      def handler():
        return payload["address"]["city"]
