apiVersion: k8s.raptor.ml/v1alpha1
kind: Feature
metadata:
  name: hello-world
spec:
  primitive: string
  freshness: 1h
  staleness: 2h
  keys:
    - name
  builder:
    code: |-
      def handler(row, ctx) -> str:
         return "Hello world " + ctx.keys["name"]
