apiVersion: k8s.raptor.ml/v1alpha1
kind: Feature
metadata:
  name: primitive-string
  namespace: default
  annotations:
    a8r.io/owner: "@AlmogBaku"
spec:
  primitive: "string"
  freshness: 10s
  staleness: 5m
  keys:
    - name
  builder:
    code: |
      def handler(row, ctx) -> str:
        return "hello"
---
apiVersion: k8s.raptor.ml/v1alpha1
kind: Feature
metadata:
  name: primitive-int
  namespace: default
  annotations:
    a8r.io/owner: "@AlmogBaku"
spec:
  primitive: "int"
  freshness: 10s
  staleness: 5m
  keys:
      - name
  builder:
    code: |
      def handler(row, ctx) -> int:
        return 1
---
apiVersion: k8s.raptor.ml/v1alpha1
kind: Feature
metadata:
  name: primitive-float
  namespace: default
  annotations:
    a8r.io/owner: "@AlmogBaku"
spec:
  primitive: "float"
  freshness: 10s
  staleness: 5m
  keys:
      - name
  builder:
    code: |
      def handler(row, ctx) -> float:
        return 1.1
---
apiVersion: k8s.raptor.ml/v1alpha1
kind: Feature
metadata:
  name: primitive-bool
  namespace: default
  annotations:
    a8r.io/owner: "@AlmogBaku"
spec:
  primitive: "bool"
  freshness: 10s
  staleness: 5m
  keys:
      - name
  builder:
    code: |
      def handler(row, ctx) -> bool:
        return True
---
apiVersion: k8s.raptor.ml/v1alpha1
kind: Feature
metadata:
  name: primitive-timestamp
  namespace: default
  annotations:
    a8r.io/owner: "@AlmogBaku"
spec:
  primitive: "timestamp"
  freshness: 10s
  staleness: 5m
  keys:
      - name
  builder:
    code: |
      def handler(row, ctx) -> datetime.datetime:
        import datetime
        return datetime.datetime.now()
---
apiVersion: k8s.raptor.ml/v1alpha1
kind: Feature
metadata:
  name: primitive-array-strings
  namespace: default
  annotations:
    a8r.io/owner: "@AlmogBaku"
spec:
  primitive: "[]string"
  freshness: 10s
  staleness: 5m
  keys:
      - name
  builder:
    code: |
      def handler(row, ctx) -> List[str]:
        return ["a","b","c"]
---
apiVersion: k8s.raptor.ml/v1alpha1
kind: Feature
metadata:
  name: primitive-array-ints
  namespace: default
  annotations:
    a8r.io/owner: "@AlmogBaku"
spec:
  primitive: "[]int"
  freshness: 10s
  staleness: 5m
  keys:
      - name
  builder:
    code: |
      def handler(row, ctx) -> List[int]:
        return [1,2,3]
---
apiVersion: k8s.raptor.ml/v1alpha1
kind: Feature
metadata:
  name: primitive-array-floats
  namespace: default
  annotations:
    a8r.io/owner: "@AlmogBaku"
spec:
  primitive: "[]float"
  freshness: 10s
  staleness: 5m
  keys:
    - name
  builder:
    code: |
      def handler(row, ctx) -> List[float]:
        return [1.4,2.0,3.2]
---
apiVersion: k8s.raptor.ml/v1alpha1
kind: Feature
metadata:
  name: primitive-array-bools
  namespace: default
  annotations:
    a8r.io/owner: "@AlmogBaku"
spec:
  primitive: "[]bool"
  freshness: 10s
  staleness: 5m
  keys:
    - name
  builder:
    code: |
      def handler(row, ctx) -> List[bool]:
        return [True, False, False]
---
apiVersion: k8s.raptor.ml/v1alpha1
kind: Feature
metadata:
  name: primitive-array-timestamps
  namespace: default
  annotations:
    a8r.io/owner: "@AlmogBaku"
spec:
  primitive: "[]timestamp"
  freshness: 10s
  staleness: 5m
  keys:
    - name
  builder:
    code: |
      def handler(row, ctx) -> List[datetime.datetime]:
        from datetime import datetime
        now = datetime.now()
        return [now, now+1, now+2]
