## Append samples you want in your CSV to this file as resources ##
resources:
  - feature.basic.simple-aggr.yaml
  - feature.basic.hello-world.yaml
  - feature.basic.primitives.yaml
  - feature.rest.user-city.yaml
  - model.basic.yaml
  - src.streaming.clicks.yml
  - src.rest.placeholder.yml
#+kubebuilder:scaffold:manifestskustomizesamples
