apiVersion: k8s.raptor.ml/v1alpha1
kind: Model
metadata:
  name: model-basic
spec:
  freshness: 1h
  staleness: 1h
  timeout: 1s
  features:
    - hello_world
    - simple_aggr
  modelServer: sagemaker-ack
  modelFramework: sklearn
  modelFrameworkVersion: 1.0-1
  storageURI: s3://my-bucket/model
  inferenceConfig:
    - name: region
      value: us-east-1
    - name: executionRoleARN
      value: arn:aws:iam::123456789012:role/MyRole
