apiVersion: k8s.raptor.ml/v1alpha1
kind: DataSource
metadata:
  name: clicks
spec:
  kind: streaming
  config:
    - name: kind
      value: kafka
    - name: brokers
      value: :9093
    - name: topics
      value: clickstream
    - name: consumer_group
      value: clicks-consumer-group
    - name: tls_disable
      value: "true"
  keyFields:
    - client_id
  timestampField: timestamp
  schema: https://raw.githubusercontent.com/raptor-ml/massivedynamic-protos/master/click.proto#Click
