apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-core
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-core
  namespace: system
  labels:
    control-plane: controller-core
spec:
  selector:
    matchLabels:
      control-plane: controller-core
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: core
      labels:
        control-plane: controller-core
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: core
        command:
        - /core
        image: controller:latest
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 50m
            memory: 1028Mi
      serviceAccountName: controller-core
      terminationGracePeriodSeconds: 10
