resources:
- core.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
- name: controller
  newName: ghcr.io/natun-ai/natun-core
  newTag: latest

replicas:
  - name: core
    count: 3

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
