resources:
- core.yaml
- service.yaml
- webhook-server-cert.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
- name: raptor-core
  newName: raptor-core
  newTag: latest
- name: raptor-runtime
  newName: raptor-runtime
  newTag: latest-python3.11

replicas:
- count: 3
  name: controller-core

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
