apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: system
  labels:
    app: core
spec:
  ports:
    - name: grpc
      port: 60000
      protocol: TCP
      targetPort: grpc
    - name: http
      port: 60001
      protocol: TCP
      targetPort: http
  selector:
    control-plane: controller-core
