name: OSS Licenses Check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  allowed-licenses:
    runs-on: ubuntu-latest
    name: Check for allowed licenses
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - name: Clone the code
        uses: actions/checkout@v3
      - name: Install google/go-licenses
        run: go install github.com/google/go-licenses@master
        shell: bash
      - name: Check for licenses
        run: ./hack/licenses-check-allowed.sh
        shell: bash