on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  license-check:
    runs-on: ubuntu-latest
    name: License Check
    steps:
      - uses: actions/checkout@v2
      - uses: yusufpapurcu/go-license-checker@v0.5