name: License Header

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  license-header:
    runs-on: ubuntu-latest
    name: License Header
    steps:
      - name: Clone the code
        uses: actions/checkout@v3
      - name: Check for license header
        run: ./hack/check-headers-for-license.sh
        shell: bash
      - name: Report failure
        if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 🐛 License header missing for ${{ github.sha }}
          body: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          labels: bug