name: Lint

# Trigger the workflow on pull requests and direct pushes to any branch
on:
  push: ~
  pull_request: ~

jobs:

  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    # Pull requests from the same repository won't trigger this checks as they were already triggered by the push
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - name: Clone the code
        uses: actions/checkout@v3
      - name: Cache binaries
        uses: actions/cache@v3
        with:
          path: bin/
          key: ${{ runner.os }}-bin-${{ hashFiles('bin/**') }}
          restore-keys: |
            ${{ runner.os }}-bin-
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Make generate
        run: make generate
        shell: bash
      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest        # Always uses the latest patch version.
          only-new-issues: true # Show only new issues if it's a pull request
          args: --timeout=3m
      - name: Report failure
        uses: nashmaniac/create-issue-action@v1.1
        # Only report failures of pushes (PRs have are visible through the Checks section) to the default branch
        if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          title: 🐛 Lint failed for ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: kind/bug
          body: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}