kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: raptor
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80 # http ingress
        hostPort: 80
        protocol: TCP
      - containerPort: 443 # https ingress
        hostPort: 443
        protocol: TCP
      - containerPort: 32094 # redis
        hostPort: 6379
        protocol: TCP
      - containerPort: 32006 # accessor grpc
        hostPort: 32006
        protocol: TCP